theme: jekyll-theme-minimal
title: Fortuna Personal Budget Solution
description: Fortuna is a flexible tool designed to effectively aid in everyday budgeting by using a form of bucket budgeting, a transparent and realistic approach to managing your income and expenses.
